server:
  username: loginUsername
  password: 'loginPassword'
  smpt_server: yourSMTPserver

mail:
  subject: Email subject
  sender: loginUsernameIfEmail
  sender_name: senderName
  to: sendToEmail
  text: Simple text of the email

sms:
  api_url: "UrlApiWithCredentials"
  to: "RecipientWithRecipientKey"
  message: "MessageWithMessageKey"

raspberry:
  pin: 7